### ISSUE TITLE
MIN:on_inner_dp_join() fired even if forwarder is leaving topology

### ISSUE THREAD

**Issue by nadicek** [unifycore/ryu#4]
In "forwarder_state_changed" function,  the "on_inner_dp_join" fuction is called regardless whether the forwarder joins the topology or leaves the topology. This makes no sence in my opinion.
To be discussed with Martin K. and fixed.
- source: /ryu/ryu/app/magic.py

**Comment by ghost** [comment]
You are of course right, on_inner_dp_join() is now called only when dp is joining topology.

Sidenote: We still have to fully address case when forwarder gets disconnected from topology. For now it's only removed from topology but we must consider impact on existing tunnels and PDP Contexts, I'll make separate case for it.
