### ISSUE TITLE
MIN: Topology handling (del_forwarder method)

### ISSUE THREAD

**Issue by nadicek** [unifycore/ryu#5]
Method del_forwarder actually removes all the links of the forwarder but not the forwarder itself. Therefore after for example crash of the forwarder, the new shortest path routes will be calculated correctly, but the StaticGraph and DynamicGraph objects will hold incorrect data (forwarder/node which actually does not exist)
Clarify existing solution and fix it...one liner
- souce /ryu/ryu/app/magic.py

**Comment by ghost** [comment]
Issue fixed, theres actualy a built-in function remove_node() in networkx.DiGraph that takes care of removing both node and its adjecent edges from graph. del_forwarder() is now glorified wrapper for this function :D
